# MangoHud Global Config
toggle_hud=F12
toggle_fps_limit=F1
fps_limit=0
gpu_stats
gpu_temp
cpu_stats
cpu_temp
ram
vram
fps
frametime=0
frame_timing
position=top-left
font_size=20
background_alpha=0.3
